language: python
python:
  - 3.5
  - 3.8
env:
- TOXENV=django22
- TOXENV=quality
install:
- pip install pip==20.0.2
- make requirements
script:
- tox
deploy:
  provider: pypi
  user: edx
  password:
    secure: qhgSqrSxjfHxTBvE9ioFnlVvmUPYdKrdpgvmJr/2ZukbCwqdS9w+S8tmtuRkvKuKGTZYp4im138oOAO6OFSLnC95nyWTb1vsC1SeUj544XxgbTsO5JILE9revU/p9vdkBepLzG0oz2Rj1N6h9qrCCc5GKpS7UMuz9Oxli+pbLRU=
  on:
    tags: true
    python: 3.5
    condition: "$TOXENV = django22"
    distributions: sdist bdist_wheel
    repo: edx/django-lang-pref-middleware
